# 사이트 기본 설정

# 사용할 테마를 불러옵니다.
theme: jekyll-theme-chirpy

# 웹사이트의 언어 설정 › http://www.lingoes.net/en/translator/langcode.htm
# `_data/locales` 폴더 내 파일 이름과 동일할 경우, 해당 언어로 레이아웃 언어가 설정됩니다.
# 해당되지 않으면 기본값인 'en'이 사용됩니다.
lang: ko-KR

# 시간대 설정 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Seoul
future: true

# jekyll-seo-tag 설정 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 늙고 병든 공부방

tagline: 여기저기 잔병 많은 사람의 노트  # 사이트 부제목으로 표시됩니다.

description: >-  # SEO 메타와 Atom 피드에서 사용됨
  허리 아파

# 사이트의 프로토콜과 도메인 주소를 입력하세요.
# 예: 'https://username.github.io' (마지막에 '/'는 넣지 않습니다)
url: "https://ksm008.github.io/"

github:
  username: ksm008  # 본인의 GitHub 사용자 이름으로 변경하세요.

social:
  # 전체 이름을 입력하세요.
  # 게시물의 기본 작성자 및 사이트 하단 저작권 소유자로 표시됩니다.
  name: KwonSeungMin
  email: resbik@naver.com  # 이메일 주소를 입력하세요.
  links:
    # 첫 번째 링크는 저작권 소유자의 링크로 사용됩니다.
    - https://github.com/ksm008
    # 아래 줄의 주석을 해제해 추가 소셜 링크를 입력할 수 있습니다.
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# 사이트 인증 설정
webmaster_verifications:
  google:  # 구글 인증 코드 입력
  bing:    # Bing 인증 코드 입력
  alexa:   # Alexa 인증 코드 입력
  yandex:  # Yandex 인증 코드 입력
  baidu:   # Baidu 인증 코드 입력
  facebook: # Facebook 인증 코드 입력

# ↑ --------------------------
# jekyll-seo-tag 설정 종료

# 웹 분석 도구 설정
analytics:
  google:
    id:  # Google Analytics ID 입력
  goatcounter:
    id:  # GoatCounter ID 입력
  umami:
    id:     # Umami ID 입력
    domain: # Umami 도메인 입력
  matomo:
    id:     # Matomo ID 입력
    domain: # Matomo 도메인 입력
  cloudflare:
    id:     # Cloudflare Web Analytics 토큰 입력
  fathom:
    id:     # Fathom 사이트 ID 입력

# 페이지 뷰 설정
pageviews:
  provider:  # 현재는 'goatcounter'만 지원함

# 색상 테마 기본값 설정
#
# 비워두면 시스템 기본 테마를 따릅니다.
# 사이드바 왼쪽 하단에 테마 전환 토글이 표시됩니다.
#
# 사용할 수 있는 옵션:
#
#     light — 밝은 테마 사용
#     dark  — 어두운 테마 사용
#
theme_mode: # [light | dark]

# 미디어 리소스용 CDN 주소
# 설정하면, '/'로 시작하는 모든 미디어 경로에 CDN 주소가 붙습니다.
#
# 예: 'https://cdn.com'
cdn:

# 사이드바에 표시될 프로필 이미지 (로컬 파일 또는 외부 리소스 가능)
avatar: /assets/img/avatar.jpg
favicon: "/favicon.ico"

# SEO의 og:image 메타 태그에 사용될 사이트 전역 대표 이미지 URL
# 게시물 개별 front matter의 `page.image`로 덮어쓸 수 있음
social_preview_image:

# 게시글에서 TOC(목차) 전역 사용 여부
toc: true

# 댓글 시스템 설정 (전역 스위치). 비워두면 비활성화됨.
comments:
  provider:  "giscus"
  # 댓글 제공자 별 설정
  giscus:       # giscus 설정 › https://giscus.app
    repo: "ksm008/ksm008.github.io"  # GitHub 저장소 이름
    repo_id: "R_kgDOPQAACQ"
    category: "Announcements"  # 댓글 카테고리 이름
    category_id: "DIC_kwDOPQAACc4CtW3x"
    mapping: pathname # 선택값. 기본은 'pathname'
    strict: 0  # 선택값. 기본은 '0'
    input_position: bottom # 선택값. 기본은 'bottom'
    lang: "ko"    # 선택값. 기본은 `site.lang`
    reactions_enabled: true
    metadata_enabled: false
    theme:
      light: "light"
      dark: "dark_dimmed"

# 정적 파일 자체 호스팅 설정 › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:  # true일 경우 자체 호스팅 활성화
    env:      # 사용할 Jekyll 환경 (비워두면 둘 다 적용됨) [development | production]

# PWA(설치형 웹앱) 기능
pwa:
  enabled: true  # PWA 기능 전체 사용 여부
  cache:
    enabled: true  # 오프라인 캐시 기능 사용 여부
    deny_paths:
      # - "/example"  # `<사이트주소>/example/*` 경로는 캐시 대상에서 제외됨

# 한 페이지에 보여줄 게시글 수
paginate: 10

# 사이트의 기본 경로
baseurl: ""

mathjax: true

# -------------- 아래 항목들은 수정 권장하지 않음 ------------------

kramdown:  # 마크다운 렌더링 옵션
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:  # Rouge 하이라이터 옵션 › https://github.com/jneen/rouge#full-options
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:  # Chirpy의 탭 기능 사용 시
  tabs:
    output: true
    sort_by: order

defaults:  # 기본 레이아웃 및 permalink 설정
  - scope:
      path: ""  # 빈 문자열은 전체 폴더 적용 의미
      type: posts
    values:
      layout: post
      comments: true  # 게시글에서 댓글 사용
      toc: true       # 게시글에서 목차 표시
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:  # Sass 스타일 설정
  style: compressed

compress_html:  # HTML 압축 설정
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]  # 개발 환경에서는 압축 제외

exclude:  # Jekyll 빌드 시 제외할 파일/폴더
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
  - 개인 노트

jekyll-archives:  # 태그/카테고리 페이지 설정
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
